# Verifying Your API Connection
The purpose of this notebook is to verify that you can access the [Dimensions Analytics API](https://www.dimensions.ai/dimensions-apis/) using Python. 

> **Please note** only Dimensions users with an Analytics API subscription can access this service. 

### Technical prerequisites
This guide assumes that you already have a Python 3 working environment and [pip](https://pypi.org/project/pip/) (the python package manager) installed. For more background, see this [link](https://realpython.com/installing-python/).

The only library needed for this exercise is `requests`, which can be installed as follows


In [ ]:
!pip install requests 

In [ ]:
import requests

In [1]:
import datetime
print("==\nCHANGELOG\nThis notebook was last run on %s\n==" % datetime.date.today().strftime('%b %d, %Y'))

==
CHANGELOG
This notebook was last run on Jan 24, 2022
==


### Connecting to the API using a `key`

If you have access to the Analytics API, simply get an API key from the Dimensions webapp (My Account > General Settings > API key and click "Create API key") and fill in the parameters below with your details (see also [this page](https://dimensions.freshdesk.com/support/solutions/articles/23000018791)). 



In [ ]:
KEY = 'your API key'            # your private API key
ENDPOINT = 'app.dimensions.ai'  # the Dimensions server you are using

Now try running the script below to verify your connection.


In [ ]:
#   The credentials to be used
login = {
    'key': KEY
}

#   Send credentials to login url to retrieve token. Raise
#   an error, if the return code indicates a problem.
#   Please use the URL of the system you'd like to access the API
#   in the example below.
resp = requests.post(f'https://{ENDPOINT}/api/auth.json', json=login)
resp.raise_for_status()

#   Create http header using the generated token.
headers = {
    'Authorization': "JWT " + resp.json()['token']
}

#   Execute DSL query.
resp = requests.post(
    f'https://{ENDPOINT}/api/dsl.json',
    data='search publications for "乳がん" return publications'.encode(),
    headers=headers)

#   Display raw result
print(resp.json())

{'_stats': {'total_count': 103121703}, 'publications': [{'title': 'Sure 16,1 - 23,118', 'type': 'book', 'id': 'pub.1113244530', 'year': 2019}, {'title': 'Deutungsmacht von Zeitdiagnosen', 'type': 'book', 'id': 'pub.1113146259', 'year': 2019}, {'title': '“So You Want to Write about American Indians?” Ethical Reflections on Euro-Academia’s Research on Indigenous Cultural Narratives', 'author_affiliations': [[{'first_name': 'Amina', 'last_name': 'Grunewald', 'orcid': '', 'current_organization_id': '', 'researcher_id': '', 'affiliations': []}]], 'type': 'chapter', 'id': 'pub.1113271690', 'pages': '239-260', 'year': 2019}, {'title': 'The Moral Nexus', 'author_affiliations': [[{'first_name': 'R. Jay', 'last_name': 'Wallace', 'orcid': '', 'current_organization_id': '', 'researcher_id': '', 'affiliations': []}]], 'type': 'monograph', 'id': 'pub.1117142285', 'year': 2019}, {'title': 'VC', 'author_affiliations': [[{'first_name': 'Tom', 'last_name': 'Nicholas', 'orcid': '', 'current_organization_

If the details are correct, you should see some JSON results being returned, which looks like this 

```
{'_stats': {'total_count': 103121703}, 'publications': [{'title': 'Sure 16,1 - 23,118', 'type': 'book', 'id': 'pub.1113244530', 'year': 2019}, {'title': 'Deutungsmacht von Zeitdiagnosen', 'type': 'book', 'id': 'pub.1113146259', 'year': 2019}, {'title': '“So You Want to Write about American Indians?” Ethical Reflections on Euro-Academia’s Research on Indigenous Cultural Narratives', 'author_affiliations': ....
```

### Legacy authentication method: username & password

Some legacy users may still have to authenticate using their Dimensions **username** and **password**. 

If that’s the case, simply replace the beginning of the snippet above as follows:

In [1]:
#   Deprecated method if you don't have a key 

login = {
    'username': 'ENTER YOUR USERNAME HERE',
    'password': 'ENTER YOUR PASSWORD HERE'
}

#   Send credentials to login url to retrieve token. Raise
#   an error, if the return code indicates a problem.
#   Please use the URL of the system you'd like to access the API
#   in the example below.
resp = requests.post(f'https://{ENDPOINT}/api/auth.json', json=login)
resp.raise_for_status()

#   Create http header using the generated token.
headers = {
    'Authorization': "JWT " + resp.json()['token']
}

#   Execute DSL query.
resp = requests.post(
    f'https://{ENDPOINT}/api/dsl.json',
    data='search publications for "乳がん" return publications'.encode(),
    headers=headers)

#   Display raw result
print(resp.json())

### Troubleshooting 

If you get an error it may be for any of these reasons:

* your Dimensions credentials do not support API access
* you mispelled your key 
* you mispelled the endpoint URL (if unknown, you can try 'app.dimensions.ai')
* you don't have a working internet connection 

It's also useful to take a look at the [API official documentation](https://docs.dimensions.ai/dsl/api.html) as there various other way to test your API connection. 